### ISSUE TITLE
UCP - alerts -> check for new alerts

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#177]
When you click on link to check for a new alerts in UCP - alerts disappear (not all, some of them stay). You have to press F5 (refresh) and they are back...

**Comment by euantorano** [comment]
Interesting. I'm going to assume another JS issue.

**Comment by Cu8eR** [comment]
Yes, obviously :(

**Comment by WhiteNeo** [comment]
I made small changes on js and css files, and core myalerts.php plugin file additions, but i do not know how to send it,  But the change codes are very easy to find, well i update my own fork when have time to put the latest files used on my site, because some changes on official core files have to be done, and i´ve done on latest files, but do not upload yet.

This i think can fix the js errors. (js changes senden today to my own forked version of my alerts)

**Comment by Cu8eR** [comment]
@WhiteNeo - push them to your fork, I can easily create a PR here if you wanna help from me... same like last PR from you.

**Comment by WhiteNeo** [comment]
Yes i find a moment to learn how to use github, but at this moment i have to test files due my host uses cloudflare and got cache so, i can not test to see if eorks propertly.

I only figured out to retrieve right data on localhost but without more alerts can not confirm if was ok, on past code pnly retrieves one data and loads it on page via ajax, right now i retrieve 3 to 5, like the query asumes to retrieve and prepends to list using ajax, so if you got 10 new alerts i supose only 5 was loaded, the latest alerts due this query and 5 are pendant, loading the same old data near the new ones, this i have to be sure it's working on and ready to use on live boards, when my host updates cache files i do dome tests to confirm if data loadings has allright.

When i finish some tests the upload all files and learn how to send pull requests to send all changes i made to give a rest to Euan T and a break, because i know how hard is when you have many tasks on your life.

**Comment by WhiteNeo** [comment]
Nope, array is empty and not retrieve missing data, i am reviewing why and try to understand source code to try a new code or some fix if i can do it...

I am testing and data was missing allways, only get one data and another data was missing everytime. 

And in this code changes all alerts was missing, if have old alerts, only load new alerts...
