### ISSUE TITLE
BLANK page in ACP -> Plugins

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#276]
![image](https://user-images.githubusercontent.com/778890/164987449-68bf66e0-2995-45af-85a4-19604c6a948c.png)

Plugin is not activated/installed... just copied on server.

**Comment by Eldenroot** [comment]
OK, Classloader was outdated... anyway there should be some notice to admins or at least bundled tofgether with myalerts.

**Comment by euantorano** [comment]
It’s difficult to show a notice or warning to admins - the blank page is caused by a PHP error. If you enabled error reporting and display_errors in your PHP.ini then the error message would show but that isn’t a good idea either. 

It isn’t bundled on GitHub, as it’s a separate project. 

Glad you got it fixed!

**Comment by Eldenroot** [comment]
@euantorano - thx for the reply! I am still waiting for 2.0.5 release because it should fix all the annoying issues and improve the usability :(

**Comment by euantorano** [comment]
You can just use the code from GitHub without a formal release process. 

I need to find some time to do a proper release at some point though.

**Comment by Eldenroot** [comment]
I would be really grateful if you can find some time and pick some issues from the mislestones 2.0.5 and 2.1.0 - we do not need new features, we just need to make it usable and user friendly :)
