### ISSUE TITLE
Unknown column 'myalerts_disabled_alert_types' in 'field list'

### ISSUE THREAD

**Issue by Splicho** [MyBBStuff/MyAlerts#296]
Hey, me again, sorry.

But after trying to post a reply, I get the follow error message.
I have executed the SQL query that came with the package, but there was no `myalerts_disabled_alert_types` column included.

![brave_khfqIeVRg4](https://github.com/MyBBStuff/MyAlerts/assets/4650700/eb2217cf-9a21-408f-8baa-45894c8847f9)

Do I need to run another query?

**Comment by lairdshaw** [comment]
You shouldn't (need to) run any queries manually in the first place. The plugin runs the queries it needs upon installation. Try uninstalling and reinstalling MyAlerts (via the ACP's Plugins page).

**Comment by euantorano** [comment]
Hi,The plug-in install (done via the ACP) should have added this column. Since it looks like it didn’t, you can add it manually with this SQL:ALERT TABLE mybb_users ADD myalerts_disabled_alert_types TEXT;On 14 Jul 2023, at 03:03, Splicho ***@***.***> wrote:﻿

Hey, me again, sorry.
But after trying to post a reply, I get the follow error message.
I have executed the SQL query that came with the package, but there was no myalerts_disabled_alert_types column included.
Do I need to run another query?

**Comment by Splicho** [comment]
Hey. Issue seems to be resolved!
            
            
                
                    Von: "Euan Torano" ***@***.***>Datum: 14. Juli 2023An: "MyBBStuff/MyAlerts" ***@***.***>Cc: "Author" ***@***.***>,"Splicho" ***@***.***>Betreff: Re: [MyBBStuff/MyAlerts] Unknown column 'myalerts_disabled_alert_types' in 'field list' (Issue #296)
                
                
Hi,The plug-in install (done via the ACP) should have added this column. Since it looks like it didn’t, you can add it manually with this SQL:ALERT TABLE mybb_users ADD myalerts_disabled_alert_types TEXT;On 14 Jul 2023, at 03:03, Splicho ***@***.***> wrote:﻿



Hey, me again, sorry.

But after trying to post a reply, I get the follow error message.

I have executed the SQL query that came with the package, but there was no myalerts_disabled_alert_types column included.

Do I need to run another query?
